### PR TITLE
Add multi-target support; Lower FSharp.Core version

### PR DESCRIPTION
**Pull request by eiriktsarpalis**

### CODE REVIEW

**Comment by alfonsogarciacaro** [comment]
Thanks! This should fix #6. Does it require something in particular for publishing or `dotnet pack` command works normally?

**Comment by eiriktsarpalis** [comment]
It should work same as before :-)

**Comment by alfonsogarciacaro** [comment]
I think I need to set an env var to make multitarget building work with Mono, but I forgot which one... Will publish from Windows for now.

**Comment by bartelink** [comment]
something [like this](https://github.com/jet/equinox/blob/92c8b878ba93b01f045d2c7f9a3af6ceb736dcf9/build.ps1#L17) ?

**Comment by alfonsogarciacaro** [comment]
Yes, that's the one, thank you!

**Pull request merged**
